site_name: CSPA Website Docs
site_url: https://cspadocs.readthedocs.io/
repo_url: https://github.com/mojeedoyedeji/cspa.docs
docs_dir: docs/source/content

theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  #- markdown_include.include:
  #   base_path: .
  - admonition

nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/introduction.md
      - Roles & Permissions: getting-started/roles.md
      - Site Structure Overview: getting-started/structure.md
  - Content Management:
      - Homepage:
          - Header, Footer, Middle: content/homepage/layout.md
          - News Section Setup: content/homepage/news.md
          - Newsletter Embeds: content/homepage/newsletter.md
      - About Us:
          - Overview: content/about-us/index.md
          - Who we are: content/about-us/who-we-are.md
          - What we do: content/about-us/what-we-do.md
          - Affiliate members: content/about-us/affiliate-members.md
          - Sponsors: content/about-us/sponsors.md
          - Our Network: content/about-us/our-network.md
      - Skin, Hair and Nails:
          - Overview: content/conditions/index.md
      - Education:
          - Overview: content/education/index.md
      - Advocacy:
          - Overview: content/advocacy/index.md
      - Research:
          - Overview: content/research/index.md
      - Advocacy:
          - Overview: content/conditions/index.md
      - Get Involved:
          - Overview: content/get-involved/index.md
          - Add Patient Stories: content/get-involved/patient-stories.md

  - Forms & Integrations:
      - Open Surveys Page: integrations/surveys.md
      - Get the Magazine (Mailchimp): integrations/magazine-signup.md

  - Maintenance:
      - Content Update Checklist: maintenance/content-checklist.md
      - Accessibility & SEO: maintenance/accessibility-seo.md
      - Link Monitoring: maintenance/link-checker.md
  - Advanced:
      - Embedding Third-Party Widgets: advanced/widgets.md
      - Custom JS/CSS: advanced/custom-code.md
      - Analytics Integration: advanced/analytics.md
  - References:
      - Glossary: references/glossary.md
      - Contributor Guide: references/contributors.md
      - Contact & Support: references/support.md
